//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WinOdataBc.DataToBCService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DataToBc_Binding", Namespace="urn:microsoft-dynamics-schemas/codeunit/DataToBc")]
    public partial class DataToBc : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetFieldsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFunctionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DataToBc() {
            this.Url = global::WinOdataBc.Properties.Settings.Default.WinOdataBc_DataToBCService_DataToBc;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetFieldsCompletedEventHandler GetFieldsCompleted;
        
        /// <remarks/>
        public event GetFunctionsCompletedEventHandler GetFunctionsCompleted;
        
        /// <remarks/>
        public event CreateCompletedEventHandler CreateCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/DataToBc:GetFields", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/DataToBc", ResponseElementName="GetFields_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/DataToBc", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GetFields(string type, bool direct) {
            object[] results = this.Invoke("GetFields", new object[] {
                        type,
                        direct});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetFieldsAsync(string type, bool direct) {
            this.GetFieldsAsync(type, direct, null);
        }
        
        /// <remarks/>
        public void GetFieldsAsync(string type, bool direct, object userState) {
            if ((this.GetFieldsOperationCompleted == null)) {
                this.GetFieldsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFieldsOperationCompleted);
            }
            this.InvokeAsync("GetFields", new object[] {
                        type,
                        direct}, this.GetFieldsOperationCompleted, userState);
        }
        
        private void OnGetFieldsOperationCompleted(object arg) {
            if ((this.GetFieldsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFieldsCompleted(this, new GetFieldsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/DataToBc:GetFunctions", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/DataToBc", ResponseElementName="GetFunctions_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/DataToBc", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GetFunctions() {
            object[] results = this.Invoke("GetFunctions", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetFunctionsAsync() {
            this.GetFunctionsAsync(null);
        }
        
        /// <remarks/>
        public void GetFunctionsAsync(object userState) {
            if ((this.GetFunctionsOperationCompleted == null)) {
                this.GetFunctionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFunctionsOperationCompleted);
            }
            this.InvokeAsync("GetFunctions", new object[0], this.GetFunctionsOperationCompleted, userState);
        }
        
        private void OnGetFunctionsOperationCompleted(object arg) {
            if ((this.GetFunctionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFunctionsCompleted(this, new GetFunctionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/DataToBc:Create", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/DataToBc", ResponseElementName="Create_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/DataToBc", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Create(string type, string jsonString, bool directCreate) {
            this.Invoke("Create", new object[] {
                        type,
                        jsonString,
                        directCreate});
        }
        
        /// <remarks/>
        public void CreateAsync(string type, string jsonString, bool directCreate) {
            this.CreateAsync(type, jsonString, directCreate, null);
        }
        
        /// <remarks/>
        public void CreateAsync(string type, string jsonString, bool directCreate, object userState) {
            if ((this.CreateOperationCompleted == null)) {
                this.CreateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateOperationCompleted);
            }
            this.InvokeAsync("Create", new object[] {
                        type,
                        jsonString,
                        directCreate}, this.CreateOperationCompleted, userState);
        }
        
        private void OnCreateOperationCompleted(object arg) {
            if ((this.CreateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetFieldsCompletedEventHandler(object sender, GetFieldsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFieldsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFieldsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetFunctionsCompletedEventHandler(object sender, GetFunctionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFunctionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFunctionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void CreateCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591